recorder:
  id: node_01
  max_limit: 10
  debug: false
  post_mp4_convert: true
  custom_chrome_path: "/usr/bin/google-chrome-stable"
  width: 1920
  height: 1080
  xvfb_dpi: 96
  copy_to_path:
    main_path: "/app/recording_files"
    sub_path: "node_01"

log_settings:
  log_file: "./logs/recorder.log"
  maxsize: 20
  maxbackups: 4
  maxage: 2
  log_level: "info"

ffmpeg_settings:
  recording:
    pre_input: "-loglevel error -thread_queue_size 512 -draw_mouse 0"
    post_input: "-c:v libx264 -x264-params keyint=120:scenecut=0 -preset veryfast -crf 23 -c:a aac -af highpass=f=200,lowpass=f=4000,afftdn -async 1 -movflags frag_keyframe+empty_moov+default_base_moof -flush_packets 1 -tune zerolatency -y"
  post_recording:
    pre_input: "-loglevel error"
    post_input: "-preset veryfast -movflags faststart -y"
  rtmp:
    pre_input: "-loglevel error -draw_mouse 0"
    post_input: "-c:v libx264 -pix_fmt yuv420p -x264-params keyint=120:scenecut=0 -b:v 2500k -video_size 1920x1080 -c:a aac -b:a 128k -ar 44100 -af highpass=f=200,lowpass=f=4000,afftdn -preset veryfast -crf 23 -async 1 -movflags frag_keyframe+empty_moov+default_base_moof -bufsize 5000k -flush_packets 1 -tune zerolatency -f flv"

WeMeet_info:
  host: "http://wemeet-api:8080"
  api_key: "wemeet"
  api_secret: "zumyyYWqv7KR2kUqvYdq4z4sXg7XTBD2ljT6"

nats_info:
  nats_urls:
    - "nats://nats:4222"
  num_replicas: 1
  recorder:
    recorder_channel: "recorderChannel"
    recorder_info_kv: "pnm-recorderInfo"
